# Tensor 생성
- 파이토치에서 '데이터를 저장하는 자료구조'
- 'ndarray와' 성격, 사용법이 '유사'하다.

> **pytorch의 tensor는 숫자 데이터 타입만 지원한다.**

##  원하는 형태(shape) 텐서 생성
- **torch.tensor(자료구조 \[, dtype\])**
    - '지정한 dtype'(Data type)에 맞는 Tensor객체를 생성해서 반환한다.
      
## 특정 타입의 Tensor를 직접 생성
- torch.tensor()로 생성하면서 dtype을 지정하면 아래 타입의 Tensor객체가 생성된다.
- 원하는 Type의 Tensor클래스를 이용해 직접 생성해도 된다.
- **torch.FloatTensor(자료구조)**
    - float32 타입 텐서 생성
- **torch.LongTensor(자료구조)** 
    - int64 타입 텐서생성
- 그외
    - BoolTensor(bool), CharTensor(int8), ShortTensor(int16), IntTensor(int32), DoubleTensor(float64)
    
## tensor 상태 조회
- **tensor.shape, tensor.size(\[축번호\])**
    -  tensor의 shape조회
- **tensor.dtype, tensor.type()**
    - tensor 원소들의 데이터타입 조회
    - dtype은 **data type**을 type()은 tensor **객체의 클래스 타입**을 반환한다.
- **tensor.ndim, tensor.dim()**  : tensor 차원
- **tensor.numel()**: 전체 원소 개수



In [1]:
import torch
import numpy as np

In [2]:
print('torch Data types')
print("float", torch.float16, torch.float32, torch.float64, torch.float, torch.double)
print("int:", torch.int8, torch.int16, torch.int32, torch.int64, torch.short, torch.int, torch.long)
print("uint:", torch.uint8, torch.uint16, torch.uint32, torch.uint64) # uint : 이미지
print("bool:", torch.bool)

torch Data types
float torch.float16 torch.float32 torch.float64 torch.float32 torch.float64
int: torch.int8 torch.int16 torch.int32 torch.int64 torch.int16 torch.int32 torch.int64
uint: torch.uint8 torch.uint16 torch.uint32 torch.uint64
bool: torch.bool


In [3]:
a = torch.tensor([[1,2],[3,4]], dtype=torch.float32)


print("shape:", a.shape, a.size())
print("0축 크기:", a.shape[0], a.size(0))
print("type:", a.type(), a.dtype)  # type(): Tensor 객체 타입. dtype: data type => 둘은 좀 다르다.
print('차원크기:', a.dim(), a.ndim)
print('원소개수:', a.numel())
print("device:", a.device)  # tensor를 다루는 processor(메모리위치) - cpu, cuda(gpu)

shape: torch.Size([2, 2]) torch.Size([2, 2])
0축 크기: 2 2
type: torch.FloatTensor torch.float32
차원크기: 2 2
원소개수: 4
device: cpu


In [4]:
aa = torch.tensor(range(10)) # iterable 로 생성
print(aa)
aa.type()

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


'torch.LongTensor'

In [5]:
#Float, Double(32, 64bit 실수)/Int, Long(32, 64 bit 정수) type Tensor
b = torch.FloatTensor([1,3,7])  #float32
print(b.dtype)
c = torch.IntTensor([10,20,30])    # int32
print(c.dtype)
d = torch.DoubleTensor([1, 2, 3])  # float64
print(d.dtype)
e = torch.LongTensor([10, 20, 30]) # int64
print(e.dtype)

torch.float32
torch.int32
torch.float64
torch.int64


## 동일한 값을 원소로 가지는 Tensor 생성
- **torch.zeros(\*size), zeros_like(텐서)**: 0으로 구성된 tensor 생성
- **torch.ones(\*size), ones_like(텐서)**: 1로 구성된 tensor생성
- **torch.full(size, fill_value), full_like(텐서, fill_value)**: 지정한 값으로 구성된 tensor생성
  - size 
    - shape을 지정한다.
    - zeros, ones는 가변인자이므로 축별 size를 순서대로 서정
    - full 은 tuple/list로 shape을 지정한다.
    

In [6]:
a = torch.zeros(3,2,3) # 3 x 2 x 3
a.dtype
a
torch.ones(2,3)  # 2 X 3
torch.full([3,2], fill_value=100) # 3 x 2


tensor([[100, 100],
        [100, 100],
        [100, 100]])

In [7]:
# 특정 배열과 동일한 shape의 tensor 생성.
a = torch.tensor([[1, 2],[3, 4]]) # 2 x 2

print(a.shape)
b = torch.zeros_like(a)  # a와 같은 shape, dtype 으로 생성.
b = torch.ones_like(a)
b = torch.full_like(a, 20)
print(b.shape, b.dtype)
b

torch.Size([2, 2])
torch.Size([2, 2]) torch.int64


tensor([[20, 20],
        [20, 20]])

## 동일한 간격으로 떨어진 값들로 구성된 배열생성
- **torch.arange(start=0, end, step=1)** 
- **torch.linspace(start, end, steps,)** : steps - 원소개수

In [8]:
torch.arange(10)  # end. 0 ~ 10-1 1씩 증가
torch.arange(0, 1, 0.1) # 0 ~ 1-0.1, 0.1 
torch.arange(10, 1, -1) # 10 ~ 1-(-1), -1 

tensor([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [9]:
torch.linspace(0, 10, 5) # 0 ~ 10, 5개원소
torch.linspace(0, 1, 11)


tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000, 1.0000])

## 빈 tensor 생성
- **torch.empty(\*size)**

In [10]:
torch.empty(3,2,7) # 3 X 2 X 7

tensor([[[9.8142e+21, 1.6157e-42, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00]]])

## 난수를 이용한 생성

- **torch.rand(\*size)**: 0 ~ 1사이 실수로 구성된 배열을 생성. 각 값은 균등분포를 따른다.
- **torch.randn(\*size)**: 표준정규분포(평균:0, 표준편차:1)를 따르는 실수로 구성된 배열 생성
- **torch.normal(mean=평균, std=표준편차, \*size)**: 정규분포를 따르는 실수로 구성된 배열 생성
- **torch.randint(low=0, high, size)**: 지정한 범위의 정수로 구성된 배열 생성
- **torch.randperm(n)**: 0 ~ n-1 사이의 정수를 랜덤하게 섞은 값을 원소로 가지는 배열 생성

In [11]:
torch.manual_seed(0)  # seed 설정
torch.rand(1, 3, 5) # 1 x 3 x 5
torch.randn(3, 5) # 3 X 5 (보통 -1~1. or -2~2 사이 수)
torch.normal(mean=10, std=20, size=[4, 2, 3]) # 대략 -10~30 사이
torch.randint(1, 100, (3, 3, 6))
torch.randperm(100) # 0 ~ 99 를 섞어서 구성

tensor([27,  4,  8, 64, 20, 99, 49, 98, 11, 48, 32, 18, 47, 75, 85, 26, 39, 14,
        63, 38, 66, 29, 42, 52, 35, 31, 62, 13, 10, 25, 15,  2, 86, 12, 34,  1,
        72, 44, 22, 45, 88, 43, 60, 94, 23, 53, 78, 40, 41, 96, 68, 79, 55,  9,
        92, 57, 61, 17, 84, 16, 46, 82, 80, 95,  5,  7, 90, 58, 76, 93, 81, 50,
        74, 51, 36, 83, 73, 21, 97, 33, 71, 24, 91, 54, 77, 70,  6,  0, 89, 56,
        19, 65, 87, 59, 37, 30, 67,  3, 28, 69])

In [12]:
a = torch.arange(100)
a
# a 섞기
idx = torch.randperm(100) # 0 ~ 99 섞어서 반환. -> 섞은 걸 index로 조회
idx
b = a[idx]

In [13]:
b

tensor([20, 95, 14, 55, 97,  1, 21, 99, 92, 70,  3,  6, 93, 73, 75, 53, 77, 61,
        60, 48, 67, 78, 86,  9, 34,  8, 79, 40, 51, 88, 63, 31, 30, 16, 50, 71,
         4, 42, 13,  2, 59, 98, 46,  7, 24, 26, 37, 87, 36, 38, 10, 69, 52, 66,
        58, 85, 11, 39, 35, 82, 81, 90,  0, 91, 94, 80, 62, 19, 32, 74, 12, 64,
        72, 25, 44, 49, 47, 84, 45, 18, 89, 17, 15, 83, 54,  5, 41, 22, 68, 76,
        56, 96, 27, 57, 43, 28, 23, 29, 65, 33])

## Tensor gpu/cpu 메모리로 옮기기

- pytorch는 데이터셋인 tensor를 cpu메모리와 gpu 메모리로 서로 옮길 수 있다.
    - 데이터에 대한 연산처리를 어디서 하느냐에 따라 메모리를 선택한다.
    - 장치는 문자열로 설정한다.
        - CPU 사용: "cpu"
        - nvida GPU: "cuda"
        - Apple m1: "mps"
            - pytorch 1.12 부터 지원
- 옮기기
    - tensor 생성시 `device` 파라미터를 이용해 설정
    - `tensor.to(device)`를 이용해 설정
- 현재 실행환경에서 어떤 장비를 사용할 수 있는지 확인
    - nvidia gpu 사용가능확인
        - `torch.cuda.is_available()` - nvida gpu 사용가능 여부
        - `torch.backends.mps.is_available()` - Apple Silicon 사용 가능 여부

In [14]:
import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# device = 'mps' if torch.backends.mps.is_available() else 'cpu'
# device = 'cuda' if torch.cuda.is_available() else 'mps' if torch.backends.mps.is_available() else 'cpu'
device

'cpu'

In [ ]:
t = torch.tensor([1, 2, 3], dtype=torch.float32, device=device) #생성할 때 device 지정.
print(t, t.device) # tensor가 어느 device에 있는지 확인

tensor([1., 2., 3.]) cpu


In [ ]:
t2 = t.to("cpu")  # 다른 device로 옮기기.
print(t2, t2.device)

tensor([1., 2., 3.]) cpu


## tensor를 상수로 변환
- torch.Tensor객체를 파이썬 상수로 변환.
- tensor객체.item()
    - Scalar(상수) 또는 원소가 하나인 tensor를 python 상수로 변환

In [15]:
print(torch.tensor(30)) # 0차원

tensor(30)


In [16]:
a = torch.tensor(10)  # 상수(scalar) => 0차원 Tensor
print(a, a.ndim)
print(a.item())
print(type(a), type(a.item()))

tensor(10) 0
10
<class 'torch.Tensor'> <class 'int'>


In [17]:
b = torch.tensor([[20]]) # 원소가 하나인 N차원 배열
print(b, b.dim())
print(b.item()) #원소가 하나인 배열(텐서) 변환 가능

tensor([[20]]) 2
20


In [18]:
c = torch.tensor([1, 10, 100])
print(c)
# print(c.item()) #원소가 여러개일 경우 Exception발생

tensor([  1,  10, 100])


In [19]:
# d = torch.tensor([10], device='cuda')
# print(d)
# print(d.item())

## ndarray 호환

- ndarray를 tensor로 생성
    - **torch.tensor(ndarray)**
    - **torch.from_numpy(ndarray)**
- tensor를 ndarray로 변환
    - **tensor.numpy()**
    - tensor가 gpu에 있을 경우 cpu로 옮긴 뒤 변환해야 한다.

In [20]:
import numpy as np
import torch

In [ ]:
# ndarray -> tensor
arr = np.arange(1,10)

torch.tensor(arr, dtype=torch.float32)
torch.from_numpy(arr)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# tensor -> ndarray
t = torch.randn(3,3)
print(t)
t.numpy()
# t.to("cpu").numpy()

tensor([[ 0.1765, -0.4200,  0.4300],
        [-0.3740, -0.6152, -0.3849],
        [-1.1675,  0.7993, -0.4529]])


array([[ 0.17648491, -0.42004737,  0.42996544],
       [-0.37396047, -0.61517006, -0.38486037],
       [-1.1674545 ,  0.7992595 , -0.45290565]], dtype=float32)

In [37]:
# t2 = torch.randn(2,2, device="cuda")
# t2

In [ ]:
t2.numpy() 
# t2.to("cpu").numpy()

array([[ 1.062838  ,  0.18495795],
       [-0.7774782 ,  0.06410138]], dtype=float32)

# 원소 조회및 변경 

## indexing/slicing

- 대부분 Numpy 와 동일
    - **slicing에서 step을 <u>음수로 지정할 수 없다.</u>** (역순 조회 불가)


In [40]:
torch.manual_seed(0)
t = torch.randint(-10, 10, (100, ))
t

tensor([ -6,   9,   3, -10,  -7,   9,  -3,  -7,   7,  -7,  -9,  -4,   6,   9,
          8,   6,   6,  -2,   4,   3,  -4,   9,   1,   4,  -6,  -9,  -1,  -1,
         -1, -10,  -9,   2,  -7, -10,   5,  -5,  -8,   9,   1,  -2,   8,  -7,
          6,  -1,   1,   7,  -7,   5,  -8,   1, -10,  -1,   3,  -9,   1, -10,
         -7,  -4,   6,  -3,   9,  -4,  -7,   4,   5, -10,   8,   2,  -2,   2,
          7,  -5,   0, -10,  -2,  -9,   9,   6,  -9,   0,  -8,   9,  -6,   3,
         -1,  -7,  -1,   3,   9,   8,   5,  -7,  -8,   8,   5,   6,  -4,   5,
          7,   2])

In [ ]:
t[0]
t[[1, 5, -1]] # 여러개 조회-> fancy indexing

tensor([9, 9, 2])

In [ ]:
t[:5]
t[10:15]
t[90:]
t[3:30:3]

####### step 음수 안된다. 그래서 reverse(역순 조회)가 안됨. reverse하려면 flip() 사용
# t[10:1:-2]  
t[1:10:2].flip(dims=(0,)) # dims : 처리하는 축 번호

tensor([ -7,  -7,   9, -10,   9])

In [50]:
t[1:10:2]

tensor([  9, -10,   9,  -7,  -7])

## boolean index
- 논리 연산은 &, |, ~ 을 사용한다.

In [52]:
t > 0

tensor([False,  True,  True, False, False,  True, False, False,  True, False,
        False, False,  True,  True,  True,  True,  True, False,  True,  True,
        False,  True,  True,  True, False, False, False, False, False, False,
        False,  True, False, False,  True, False, False,  True,  True, False,
         True, False,  True, False,  True,  True, False,  True, False,  True,
        False, False,  True, False,  True, False, False, False,  True, False,
         True, False, False,  True,  True, False,  True,  True, False,  True,
         True, False, False, False, False, False,  True,  True, False, False,
        False,  True, False,  True, False, False, False,  True,  True,  True,
         True, False, False,  True,  True,  True, False,  True,  True,  True])

In [51]:
# boolean index
t[t > 0]

tensor([9, 3, 9, 7, 6, 9, 8, 6, 6, 4, 3, 9, 1, 4, 2, 5, 9, 1, 8, 6, 1, 7, 5, 1,
        3, 1, 6, 9, 4, 5, 8, 2, 2, 7, 9, 6, 9, 3, 3, 9, 8, 5, 8, 5, 6, 5, 7, 2])

In [54]:
t[(t > 0) & (t < 5)]

tensor([3, 4, 3, 1, 4, 2, 1, 1, 1, 3, 1, 4, 2, 2, 3, 3, 2])

In [55]:
# boolean index 처리 함수.
t.masked_select(t > 0)

tensor([9, 3, 9, 7, 6, 9, 8, 6, 6, 4, 3, 9, 1, 4, 2, 5, 9, 1, 8, 6, 1, 7, 5, 1,
        3, 1, 6, 9, 4, 5, 8, 2, 2, 7, 9, 6, 9, 3, 3, 9, 8, 5, 8, 5, 6, 5, 7, 2])

In [56]:
t

tensor([ -6,   9,   3, -10,  -7,   9,  -3,  -7,   7,  -7,  -9,  -4,   6,   9,
          8,   6,   6,  -2,   4,   3,  -4,   9,   1,   4,  -6,  -9,  -1,  -1,
         -1, -10,  -9,   2,  -7, -10,   5,  -5,  -8,   9,   1,  -2,   8,  -7,
          6,  -1,   1,   7,  -7,   5,  -8,   1, -10,  -1,   3,  -9,   1, -10,
         -7,  -4,   6,  -3,   9,  -4,  -7,   4,   5, -10,   8,   2,  -2,   2,
          7,  -5,   0, -10,  -2,  -9,   9,   6,  -9,   0,  -8,   9,  -6,   3,
         -1,  -7,  -1,   3,   9,   8,   5,  -7,  -8,   8,   5,   6,  -4,   5,
          7,   2])

In [57]:
# 변경
t[0] = 100
t

tensor([100,   9,   3, -10,  -7,   9,  -3,  -7,   7,  -7,  -9,  -4,   6,   9,
          8,   6,   6,  -2,   4,   3,  -4,   9,   1,   4,  -6,  -9,  -1,  -1,
         -1, -10,  -9,   2,  -7, -10,   5,  -5,  -8,   9,   1,  -2,   8,  -7,
          6,  -1,   1,   7,  -7,   5,  -8,   1, -10,  -1,   3,  -9,   1, -10,
         -7,  -4,   6,  -3,   9,  -4,  -7,   4,   5, -10,   8,   2,  -2,   2,
          7,  -5,   0, -10,  -2,  -9,   9,   6,  -9,   0,  -8,   9,  -6,   3,
         -1,  -7,  -1,   3,   9,   8,   5,  -7,  -8,   8,   5,   6,  -4,   5,
          7,   2])

In [58]:
t = torch.arange(1, 10).reshape(3,3)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [59]:
# t[ 0축, 1축 ]
t[1, 2].item()
t[0, 2].item()

3

In [60]:
t[[1,0], [2,2]]  #(1,2), (0,2)
# t[[첫번째값, 두번째값]-0축, [첫번째값, 두번째값]-1축]

tensor([6, 3])

In [61]:
t[[1, 1, 2], [0, 2, 1]] # [1, 0], [1, 2], [2, 1]

tensor([4, 6, 8])

# Reshape

## shape 변경
- 원소의 개수가 변하는 shape으로는 reshape이 안된다.
- tensor객체.reshape(\*shape) / view(\*shape) 이용
    - 변환 후 값을 변경하면 원본 배열의 값도 같이 바뀐다.
 > 해결 - tensor.clone(): tensor를 복제한다.

In [62]:
a=torch.rand(12)
a2 = a.reshape(3,4)
a3 = a.reshape((3,2,2))
a4 = a.reshape((3,2,-1))  #한 개 axis는 '-1로 설정'가능하고 그럼 '계산해서 알아서 설정'해 준다.
print(a.shape, a2.size(), a3.shape, a4.shape)
               

torch.Size([12]) torch.Size([3, 4]) torch.Size([3, 2, 2]) torch.Size([3, 2, 2])


In [63]:
a5 = a.view(3,4)
a6 = a.view((3,2,2))
a7 = a.view((3,2,-1))  #한개 axis는 -1로 설정가능
print(a.shape, a5.size(), a6.shape, a7.shape)

torch.Size([12]) torch.Size([3, 4]) torch.Size([3, 2, 2]) torch.Size([3, 2, 2])


In [ ]:
a5[0, 0] = 12.1
# a2[0, 1] = 15.1

print(a5)
print(a2)
print(a)
# a를 가지고 reshape했기 때문에 원본인 a도 바뀜

tensor([[12.1000,  0.8369,  0.2820,  0.3742],
        [ 0.0237,  0.4910,  0.1235,  0.1143],
        [ 0.4725,  0.5751,  0.2952,  0.7967]])
tensor([[12.1000,  0.8369,  0.2820,  0.3742],
        [ 0.0237,  0.4910,  0.1235,  0.1143],
        [ 0.4725,  0.5751,  0.2952,  0.7967]])
tensor([12.1000,  0.8369,  0.2820,  0.3742,  0.0237,  0.4910,  0.1235,  0.1143,
         0.4725,  0.5751,  0.2952,  0.7967])


In [67]:
# tensor복사: clone() 메소드
r = a.reshape(3, 4).clone()
r[0,0] = 100.1
print(a)

tensor([12.1000,  0.8369,  0.2820,  0.3742,  0.0237,  0.4910,  0.1235,  0.1143,
         0.4725,  0.5751,  0.2952,  0.7967])


In [68]:
r

tensor([[1.0010e+02, 8.3691e-01, 2.8199e-01, 3.7416e-01],
        [2.3701e-02, 4.9101e-01, 1.2347e-01, 1.1432e-01],
        [4.7245e-01, 5.7507e-01, 2.9523e-01, 7.9669e-01]])

## dummy 축 늘리기

- None을 이용 (numpy의 newaxis 대신 None을 사용한다.)
- unsqueeze(dim=축번호)

In [72]:
import torch
a = torch.tensor([[10,20],[10,20]])
print(a.shape)

a1, a2 = a[None, :], a.unsqueeze(dim=0) # dim=정수만가능
print(a1.shape, a2.shape)

a3, a4 = a[:, :, None], a.unsqueeze(dim=-1)   # a[:, None] # 0축 :, 1축 None, 2번축 지정안함 -> 원래대로 그래서 (2, 1, 2) 가됨.
print(a3.shape, a4.shape)

a5, a6 = a3[:,None,:,:, None],  a3.unsqueeze(dim=1)  # unsqueeze(): dim=정수만가능 (한번에 dummy축은 하나만 추가가능.)
print(a5.shape, a6.shape)

torch.Size([2, 2])
torch.Size([1, 2, 2]) torch.Size([1, 2, 2])
torch.Size([2, 2, 1]) torch.Size([2, 2, 1])
torch.Size([2, 1, 2, 1, 1]) torch.Size([2, 1, 2, 1])


## dummy 축 제거
- squeeze(\[dim=축번호\]) 이용

In [76]:
t = torch.rand(3, 1, 4, 1, 5, 1)
print(t.shape)

r1 = t.squeeze() # 축을 명시 하지 않으면 모두 제거
print(r1.shape)

r2 = t.squeeze(dim=1) # 특정 axis 제거
print(r2.shape)

r3 = t.squeeze(dim=[1,3]) # 여러 axis의 dummy 축 제거
print(r3.shape)

torch.Size([3, 1, 4, 1, 5, 1])
torch.Size([3, 4, 5])
torch.Size([3, 4, 1, 5, 1])
torch.Size([3, 4, 5, 1])


# tensor 합치기
- '합치는 기준 축을 제외'한 '나머지 축의 size는 같아야' 한다.
torch.cat([tensorA, tensorB, ...], dim=0) : 기준축 default 는 0

In [78]:
a = torch.arange(10).reshape(2,5)
b = torch.arange(10,20).reshape(2,5)
c = torch.arange(20,30).reshape(2,5)
d = torch.arange(10,19).reshape(3,3)

In [81]:
torch.cat([a, b], dim=0)
# torch.cat([a, b], dim=0).shape

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [84]:
torch.cat([a, b, c], dim=0)
# torch.cat([a, b, c], dim=0).shape

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]])

In [ ]:
torch.cat([a, b], axis=1) # dim 대신 axis사용가능(pytorch에는 dim이 많이 쓰이긴 함)
# torch.cat([a, b], axis=1).shape

tensor([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
        [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [ ]:
torch.cat([a, b, c], axis=1)
# torch.cat([a, b, c], axis=1).shape

tensor([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24],
        [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19, 25, 26, 27, 28, 29]])

In [88]:
torch.cat([a, b], axis=-1)  # -1: 마지막 axis

tensor([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
        [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [89]:
a.shape, d.shape
# 합치는 기준축 이외의 축 size는 같아야 한다.
# torch.cat([a, d]) # dim=0, Error  1축 size가 달라서 Error

(torch.Size([2, 5]), torch.Size([3, 3]))

# 값의 위치(index) 변경
- tensor 원소의 index의 위치를 바꾼다.
- `tensor.transpose(axis1, axis2)` 
    - '두 축'의 자리만 변경 할 수 있다.
- `tensor.permute(axis1, axis2, axis3, ..)`
    - '두 개 이상의 축' 자리를 변경한다.

In [90]:
X = torch.arange(24).reshape(2, 3, 4)
print(X.shape)

y = X.transpose(1, 2)
print(y.shape)

z = X.permute(2, 0, 1)
print(z.shape)

torch.Size([2, 3, 4])
torch.Size([2, 4, 3])
torch.Size([4, 2, 3])


In [ ]:
X # (2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [ ]:
y # (2, 4, 3)

tensor([[[ 0,  4,  8],
         [ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11]],

        [[12, 16, 20],
         [13, 17, 21],
         [14, 18, 22],
         [15, 19, 23]]])

In [ ]:
z # (4, 2, 3)

tensor([[[ 0,  4,  8],
         [12, 16, 20]],

        [[ 1,  5,  9],
         [13, 17, 21]],

        [[ 2,  6, 10],
         [14, 18, 22]],

        [[ 3,  7, 11],
         [15, 19, 23]]])

# tensor 연산 및 주요 함수

## element-wise 연산
- tensor와 상수 연산시, tensor와 tensor간 연산시 원소별로 처리한다.
- 행렬곱 연산을 제외하고 tensor간 연산시 '피연산자 tensor간에 shape이 같아야' 한다.
    - 'shape이 다를 경우' '조건이 맞으면 broadcasting을 한 뒤에 연산'한다. (size가 다른 축의 경우 한개의 '피연산자 size가 1'일 경우 '복사하여 shape을 맞춘다'.)
    

In [96]:
import torch

a = torch.arange(10).reshape(2,5)
b = torch.arange(10,20).reshape(2,5)
c = torch.arange(50, 55)

print(a)
print(b)
print(c)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
tensor([50, 51, 52, 53, 54])


In [97]:
print(a + 100)
print(a - 100)
print(a < 5)

tensor([[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109]])
tensor([[-100,  -99,  -98,  -97,  -96],
        [ -95,  -94,  -93,  -92,  -91]])
tensor([[ True,  True,  True,  True,  True],
        [False, False, False, False, False]])


In [98]:
print(a + b)
print(a == b)

tensor([[10, 12, 14, 16, 18],
        [20, 22, 24, 26, 28]])
tensor([[False, False, False, False, False],
        [False, False, False, False, False]])


In [99]:
a.size(), c.size()

(torch.Size([2, 5]), torch.Size([5]))

In [100]:
# broadcasting
print(a + c)

tensor([[50, 52, 54, 56, 58],
        [55, 57, 59, 61, 63]])


In [102]:
c.reshape(1, -1)

tensor([[50, 51, 52, 53, 54]])

## 주요 연산함수

### 주요 상수
- torch.e: 자연상수 E
- torch.pi: 원주율

In [103]:
torch.e, np.e, torch.pi, np.pi

(2.718281828459045, 2.718281828459045, 3.141592653589793, 3.141592653589793)

#### torch.nan, torch.inf
- nan: Not a Number, 주로 결측치를 표현한다.
- inf: infinit 무한. 
    - torch.inf: 양의 무한
    - -torch.inf: 음의 무한
- torch.isnan(tensor)
    - 원소별 결측치 확인
- torch.isinf(tensor)    
    - 원소별 inf 확인

In [104]:
torch.nan, np.nan

(nan, nan)

In [105]:
torch.inf, np.inf

(inf, inf)

In [106]:
print(torch.inf > 10000000000000000, torch.inf < 10000000000)
print(-torch.inf < -1000000000000000000000, -torch.inf > 10)


True False
True False


In [107]:
print(torch.log(torch.tensor(-1))) # nan (계산결과가 없으므로-없는값-nan 반환)
print(torch.isnan(torch.tensor([1,2,torch.nan,3,4])))  # nan 여부 확인
print(torch.isinf(torch.tensor([1,2,3,4,torch.inf])))  # inf 여부 확인

tensor(nan)
tensor([False, False,  True, False, False])
tensor([False, False, False, False,  True])


## 주요 연산 함수

In [ ]:
import torch

In [ ]:
# 원소별 처리
x=torch.arange(-4, 5).reshape(3,3)
print(x)
print(torch.abs(x)) # 절대값 
print(torch.sqrt(torch.abs(x))) #  제곱근
print(torch.exp(x))  # torch.e**x
print(torch.log(torch.abs(x)))
print(torch.log(torch.exp(torch.tensor(1))))  # torch.log() 밑이 e인 로그계산
print(torch.log10(torch.tensor(10)))         # torch.log10() 밑이 10인 로그계산
print(torch.log2(torch.tensor(2)))           # torch.log2() 밑이 2인 로그계산

tensor([[-4, -3, -2],
        [-1,  0,  1],
        [ 2,  3,  4]])
tensor([[4, 3, 2],
        [1, 0, 1],
        [2, 3, 4]])
tensor([[2.0000, 1.7321, 1.4142],
        [1.0000, 0.0000, 1.0000],
        [1.4142, 1.7321, 2.0000]])
tensor([[1.8316e-02, 4.9787e-02, 1.3534e-01],
        [3.6788e-01, 1.0000e+00, 2.7183e+00],
        [7.3891e+00, 2.0086e+01, 5.4598e+01]])
tensor([[1.3863, 1.0986, 0.6931],
        [0.0000,   -inf, 0.0000],
        [0.6931, 1.0986, 1.3863]])
tensor(1.)
tensor(1.)
tensor(1.)


In [109]:
y = x + torch.randn((3,3))
print(y)
print(torch.round(y)) # 반올림
print(torch.round(y, decimals=2)) # 소수점 둘째자리 이하에서 반올림
print(torch.floor(y)) # 내림
print(torch.ceil(y)) # 올림

tensor([[-4.2973, -1.4538, -2.4308],
        [-1.5254, -0.4767,  2.6950],
        [ 2.3475,  3.5804,  3.8711]])
tensor([[-4., -1., -2.],
        [-2., -0.,  3.],
        [ 2.,  4.,  4.]])
tensor([[-4.3000, -1.4500, -2.4300],
        [-1.5300, -0.4800,  2.6900],
        [ 2.3500,  3.5800,  3.8700]])
tensor([[-5., -2., -3.],
        [-2., -1.,  2.],
        [ 2.,  3.,  3.]])
tensor([[-4., -1., -2.],
        [-1., -0.,  3.],
        [ 3.,  4.,  4.]])


### 행렬곱
- `@` 연산자 또는 `torch.matmul(tensor1, tensor2)` 함수 이용

In [ ]:
x = torch.FloatTensor([[1, 2],[3, 4],[5, 6]])
y = torch.FloatTensor([[1, 2],[1, 2],])

x.size(), y.size()

(torch.Size([3, 2]), torch.Size([2, 2]))

In [111]:
z1 = x @ y
z2 = torch.matmul(x, y)
print(z1.shape, z2.shape)
print(z1)
print(z2)

torch.Size([3, 2]) torch.Size([3, 2])
tensor([[ 3.,  6.],
        [ 7., 14.],
        [11., 22.]])
tensor([[ 3.,  6.],
        [ 7., 14.],
        [11., 22.]])


In [115]:
# Batch 행렬곱(Batch matrix muliplication) - bmm()
# 피연산자로 두개의 3차원 tensor를 axis (1, 2)를 기준으로 행렬곱을 처리한다. (batch 사이즈도 같아야 하고, 내적 조건이 맞아야 함(x(3, 4, '2'), y(3, '2', 5)))
import torch
x = torch.FloatTensor(3,4,2)
y = torch.FloatTensor(3,2,5)
z = torch.bmm(x, y)
z.shape


torch.Size([3, 4, 5])

## 기술통계함수

In [113]:
X=torch.randn(3,4)
print(X)

tensor([[ 1.0063,  0.5338, -0.0812, -0.4951],
        [ 1.9328, -1.5832, -0.5897, -0.1750],
        [ 0.3529, -0.8975, -0.6523, -0.0687]])


In [117]:
print(torch.sum(X))  # default: 전체기준으로 계산. dim=None
print(torch.sum(X, dim=1)) #dim/axis 지정: 지정한 axis의 index가 다른 값끼리 계산.
print(torch.sum(X, dim=1, keepdims=True)) # 기술통계함수들을 실행하면 차원이 줄어든다. keepdims=True로 하면 차원유지

tensor(-0.7170)
tensor([ 0.9638, -0.4152, -1.2656])
tensor([[ 0.9638],
        [-0.4152],
        [-1.2656]])


In [123]:
print(torch.mean(X)), X.mean()
print(torch.mean(X, dim=0)), X.mean(dim=0)
print(torch.mean(X, dim=0, keepdims=True)), X.mean(dim=0, keepdim=True)

tensor(-0.0597)
tensor([ 1.0973, -0.6490, -0.4411, -0.2463])
tensor([[ 1.0973, -0.6490, -0.4411, -0.2463]])


(None, tensor([[ 1.0973, -0.6490, -0.4411, -0.2463]]))

In [125]:
print(torch.std(X)) # standard deviation 표준 편차
print(torch.var(X)) # variance
print(torch.var(X, dim=0))

tensor(0.9287)
tensor(0.8625)
tensor([0.6302, 1.1667, 0.0981, 0.0493])


In [124]:
# tensor.메소드() 
print(X.sum(dim=1, keepdims=True))
print(X.mean(dim=1, keepdims=True))
print(X.std())

tensor([[ 0.9638],
        [-0.4152],
        [-1.2656]])
tensor([[ 0.2409],
        [-0.1038],
        [-0.3164]])
tensor(0.9287)


In [126]:
X

tensor([[ 1.0063,  0.5338, -0.0812, -0.4951],
        [ 1.9328, -1.5832, -0.5897, -0.1750],
        [ 0.3529, -0.8975, -0.6523, -0.0687]])

In [147]:
print(torch.max(X)) # 전체 기준 max값 계산.
print(torch.max(X, dim=0))  # 축을 지정하면 return_types.max 타입객체로 반환. max값과 max값의 index를 묶어서 반환
# print(torch.max(X, dim=1))
# print(torch.max(X, dim=1).values, torch.max(X, dim=1).indices, sep=" || ")


# print(torch.max(X, dim=0, keepdims=True))  #keepdims=True : 차원(rank)를 유지
# print(torch.max(X, dim=1, keepdims=True))

tensor(1.9328)
torch.return_types.max(
values=tensor([ 1.9328,  0.5338, -0.0812, -0.0687]),
indices=tensor([1, 0, 0, 2]))


In [132]:
print(torch.min(X))
print(torch.min(X, dim=0)) # return_types.min 타입객체로 반환. min값과 min값의 index를 묶어서 반환
# print(torch.min(X, dim=1))

tensor(-1.5832)
torch.return_types.min(
values=tensor([ 0.3529, -1.5832, -0.6523, -0.4951]),
indices=tensor([2, 1, 2, 0]))


In [137]:
X

tensor([[ 1.0063,  0.5338, -0.0812, -0.4951],
        [ 1.9328, -1.5832, -0.5897, -0.1750],
        [ 0.3529, -0.8975, -0.6523, -0.0687]])

In [140]:
print(torch.argmax(X), torch.argmin(X)) # 가장 큰 값의 인덱스
print(torch.argmax(X, dim=0)) # 각 열에서 가장 큰 값의 인덱스
print(torch.argmax(X, dim=1)) # 각 행에서 가장 큰 값의 인덱스

tensor(4) tensor(5)
tensor([1, 0, 0, 2])
tensor([0, 0, 0])


In [141]:
a = torch.max(X, dim=0)
print(a.values)
print(a.indices)

tensor([ 1.9328,  0.5338, -0.0812, -0.0687])
tensor([1, 0, 0, 2])


# autograd(자동미분)
- 자동 미분을 이용해 gradient(미분계수)를 계산하는 pytorch system.
- 딥러닝 모델에서 weight와 bias tensor들(Parameter)은 backpropagation(역전파)를 이용해 gradient를 구해서 loss가 줄어드는 방향으로 update를 하게된다.
- pytorch는 이런 미분 수행을 자동으로 처리해 준다.
    - gradient(기울기)를 구한다는 것은 미분을 한다는 것을 말한다.
- tensor가 미분 가능하려면(gradient 계산 대상 변수 ex. y_hat = w*x + b -> 계산 대상 변수 : w, b) `requires_grad=True` 로 설정되 있어야 한다. (default: False)
- y_hat(결과값)이 나올 때까지의 사용된 w, b의 도함수 True인 gradient값들을 계산 

> - **미분**
>   -  (순간) 변화율을 계산한다.
>   - $$\frac{\partial y}{\partial x}$$
>       - x에 대한 y의 변화율. 즉 x가 변하면 y는 얼마나 변할까?

In [155]:
import torch

x = torch.tensor([1.0], requires_grad=True)
print(x)

print("X의 값(데이터):", x.data)
print("계산된 X의 gradient값:", x.grad)

tensor([1.], requires_grad=True)
X의 값(데이터): tensor([1.])
계산된 X의 gradient값: None


In [ ]:
y  = x**2
# 함수의 피연산자에 requires_grad=True인 Tensor가 있으면 이 함수의 도함수(gradient 계산 함수)를 미리 생성해 결과를 저장하는 tensor(y)의 grad_fn 속성에 저장
# 'requires_grad=True' -> gradient 필요 -> 계산하는 함수를 나중에 필요할 때 만드는 게 아니라 미리 만들어 저장해놓음

y

tensor([1.], grad_fn=<PowBackward0>)

In [160]:
y.grad_fn(torch.tensor([3]))
y.grad_fn(torch.tensor([3, 7, 2]))

tensor([ 6., 14.,  4.], grad_fn=<MulBackward0>)

In [161]:
# gradient 계산 
y.backward() # dy / dx
# 계산된 gradient값을 x(requires_grad=True)의 grad 속상에 저장

In [164]:
x.data, x.grad

(tensor([1.]), tensor([2.]))

In [ ]:
x = torch.tensor([2.0], requires_grad=True)
y = torch.tensor([3.0]) # requires_grad=False

z = x - y # 결과: z.data, x에 대한 도함수: z.grad_fn 에 각각 들어감 / y에 대한 도함수: 없음
z.backward() # x에 대한 grad 값을 z.grad_fn을 이용해 계산한 뒤 x.grad에 저장

In [169]:
z.grad_fn

In [168]:
x.data, x.grad

(tensor([2.]), tensor([1.]))

In [171]:
# 선형회귀 모델 대상으로 적용
input_data = torch.tensor([30.2]) 
weight = torch.tensor([0.2], requires_grad=True)

y_pred = weight * input_data # bias = 0
print(y_pred)
print(y_pred.grad_fn)

tensor([6.0400], grad_fn=<MulBackward0>)


In [173]:
print(weight.grad)
y_pred.backward()
print(weight.grad)

None
tensor([30.2000])


In [174]:
# new weight
new_weight = weight.data - weight.grad # *학습률
new_weight 

tensor([-30.])

In [ ]:
# 편미분
# 하나의 함수에 gradient를 계산해야 하는 변수가 두 개 이상일 경우 변수 별로 따로 계산. 하나의 변수에 대한 gradient 계산시 다른 변수들은 상수로 취급

a = torch.tensor([1.0], requires_grad=True)
b = torch.tensor([2.0], requires_grad=True)

result = a * b
result.backward()

print(a.grad, b.grad)

# requires_grad=True, .backward() 어디에 적용하는지 알고 있기

tensor([2.]) tensor([1.])


## torch.no_grad() 
- no_grad()를 with 구문에서 연산을 할 경우 with block 내에서 requires_grad=True로 설정된 변수를 이용한 계산식이 있더라도 grad_fn을 생성하지 않는다. 즉 gradient를 계산하지 않는다.
- '딥러닝 모델을 평가 하거나 추론 할 때'는 'gradient를 계산할 필요가 없'(requires_grad=False)기 때문에 no_grad 구문을 사용한다.


In [ ]:
x = torch.tensor([1.0], requires_grad=True)

y = x * 2
print("결과:", y.data)
print("grad_fn:", y.grad_fn)

# y의 값 계산은 하지만 backward를 하기 위해 gradient를 만드는 것을 원치 않음 -> requires_grad=False 하면 나중에 True로 바꾸고 반복해야 함

결과: tensor([2.])
grad_fn: <MulBackward0 object at 0x000002C0FAE9C670>


In [177]:
x = torch.tensor([1.0], requires_grad=True)

with torch.no_grad(): # with 블럭 안에서는 gradient 계산 X
    y = x * 2
    print(y.data, y.grad_fn)

tensor([2.]) None


## gradient 값 초기화
- backward() 에서 계산되어 저장된 gradient값을 초기화한다.
- '반복 학습'을 할 경우 'gradient가 누적'되는 문제가 발생한다. 그래서 한번 학습이 끝나면 '다음 학습 전에 초기화'하는 작업을 해야 한다.

In [183]:
x = torch.tensor([1.0], requires_grad=True)
print(x.grad)

y = x**2 # grad_fn: 2 * x
y.backward() # grad 계산 : 2 * [1.0]

print(x.grad)

None
tensor([2.])


In [184]:
# x를 이용한 새로운 계산
## 새로운 연산 전 grad값 초기화 필요. 안 하면 이전 grad 값이 남아있어 계속 누적됨.
x.grad = None # 초기화

z = x ** 3 # grad_fn: 3 * x**2
z.backward() # x.grad: 3 * 1**2 = 3
print(x.grad)

tensor([3.])


In [ ]:
# 새로운 계산
x.grad = None

r = x**2
r.backward()
print(x.grad)


tensor([2.])
